module.exports = {
  darkMode: "class",
  content: [
    "./client/interface/**/*.html",
    "./client/**/*.py",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#e7e8e9",
        "inverse-surface": "#2e3132",
        "tertiary-container": "#246dc8",
        "tertiary-fixed": "#d6e3ff",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#f8bd2a",
        "inverse-on-surface": "#f0f1f2",
        outline: "#707a6c",
        "on-tertiary-fixed": "#001b3d",
        "surface-dim": "#d9dadb",
        "on-primary-fixed": "#002204",
        "on-secondary-container": "#6f5100",
        "primary-fixed": "#a3f69c",
        "on-surface": "#191c1d",
        "on-secondary": "#ffffff",
        "surface-container": "#edeeef",
        "inverse-primary": "#88d982",
        "surface-container-highest": "#e1e3e4",
        "primary-container": "#2e7d32",
        background: "#f8f9fa",
        error: "#ba1a1a",
        "on-secondary-fixed-variant": "#5c4300",
        "surface-variant": "#e1e3e4",
        "surface-container-low": "#f3f4f5",
        "on-primary-container": "#cbffc2",
        "on-error": "#ffffff",
        "on-secondary-fixed": "#261a00",
        "primary-fixed-dim": "#88d982",
        "on-primary-fixed-variant": "#005312",
        "on-primary": "#ffffff",
        "outline-variant": "#bfcaba",
        "surface-bright": "#f8f9fa",
        surface: "#f8f9fa",
        "error-container": "#ffdad6",
        secondary: "#795900",
        primary: "#0d631b",
        "tertiary-fixed-dim": "#a9c7ff",
        "on-background": "#191c1d",
        "on-surface-variant": "#40493d",
        "on-tertiary-container": "#edf1ff",
        "on-error-container": "#93000a",
        "secondary-fixed": "#ffdfa0",
        tertiary: "#0054a7",
        "on-tertiary": "#ffffff",
        "secondary-container": "#fec330",
        "on-tertiary-fixed-variant": "#00468c",
        "surface-tint": "#1b6d24",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Manrope"],
        body: ["Inter"],
        label: ["Inter"],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
